### ISSUE TITLE
Age of aggression/start of 100 year war causes too many notifications

### ISSUE THREAD

**Issue by bboops23** [Rystic/ATLA-restored#16]
whenever the age of agression begins i get like..a million notifications informing me of it, far far too many to click away.

**Comment by bboops23** [comment]
Well, I found a bug. I was playing the Earth King, starting at the "Fall of Chin" and got to 7 August 793. Then I got a notification that "End of Prosperity" occurred, which appears to be the start of the Fire Nation invasion and the Hundred Years' War. But the notification is being spammed and the game cannot continue. It looks to be stuck in some kind of loop to me.

**Comment by jttheghost** [comment]
FIXED in e69748669479802f8461f2d817c47e043a040f88
