### ISSUE TITLE
Overhaul Trade Routes

### ISSUE THREAD

**Issue by jttheghost** [Rystic/ATLA-restored#180]
Trade routes currently boring. See the following suggestion from discord:

I think the rework or rather an adjustment of the current trade route system could help bring some more indirect interactivity with the world. Currently the trade route that is present in the game uses the Silk Route mechanics that poorly represent the flow of goods from the Fire Nation onto the mainland of Earth Kingdom. What I suggest is to change it to the Trans-Saharan Route whose value is detrmined by various special building built along the way. At the desiganted spots in the Fire Nation one could build either directly in the tradepost or in the factory sub-holding special buildings that represent the flow of manufactured goods and increase the value. 

Also extending the route to Ba Sing Se could possibly add more places one could provide value from onto the trade route. It does look odd that the only traderoute in the game does not extend into the biggest city-complex we have present. Maybe some other places in the Earth Kingdom like mines of sort could be added too? The extant on how big this can go is quite immense but the core idea is based around Fire Nation starting points boosting trade value along the whole netowork

*Rads Notes*
It looks like you can use the [potential] argument to limit it showing up, which is a province scope and from there the [trade_route] condition to build the building and a [trade] modifier. This might require some coordination & a lot of test games to implement

**Comment by Sorogom** [comment]
Cough Cough i did this already

I will touch up on this more.
