### ISSUE TITLE
Aang looks like he's 50 when he's 13

### ISSUE THREAD

**Issue by jttheghost** [Rystic/ATLA-restored#214]
![image](https://user-images.githubusercontent.com/28493765/84583754-55a38400-adca-11ea-8931-01e09adbc5de.png)

**Comment by TypicalCrusader** [comment]
#364 confirmed that this is problem that most canon characters can experience this. Thus i request to close this issue.

**Comment by unLomTrois** [comment]
It was fixed in #489
