### ISSUE TITLE
Wafangdian / Yamada movement bug

### ISSUE THREAD

**Issue by jttheghost** [Rystic/ATLA-restored#224]
![image](https://user-images.githubusercontent.com/28493765/84616010-94077480-ae98-11ea-9c20-32f9aef4d0b1.png)

![image](https://user-images.githubusercontent.com/28493765/84616012-97026500-ae98-11ea-8aeb-6611e726179e.png)

![image](https://user-images.githubusercontent.com/28493765/84616021-a08bcd00-ae98-11ea-95e9-661338a72ebd.png)

![image](https://user-images.githubusercontent.com/28493765/84616029-a84b7180-ae98-11ea-88ab-b414f528b82b.png)

![image](https://user-images.githubusercontent.com/28493765/84616034-ad102580-ae98-11ea-8051-d44b887706dd.png)

**Comment by TypicalCrusader** [comment]
fixed
