### ISSUE TITLE
Certain cbs CTD

### ISSUE THREAD

**Issue by bboops23** [Rystic/ATLA-restored#33]
playing as Tyro ofSonid Youqi (Earliest start date), declaring war on my neighbour with "Reconquest of Chin" CB
ends instantly inconclusive (no longer valid)

**Comment by OkieMatthewHarrison** [comment]
I had trouble recreating this bug, I was able to conqure 4 counties, 2 as independent and 2 while under my liege while using the "Reconquest of Chin" CB. I was unable to recreate the bug. I am curious to see if anyone else is able to recreate the bug.
