### ISSUE TITLE
Infinitely repeating unrest messages

### ISSUE THREAD

**Issue by BastiYUQ** [Rystic/ATLA-restored#453]
There is an issue with infinitely repeating message: Unrest in the Earth Kingdom. 
I encountered this bug around an hour into the game and the messages keep popping up constantly. 

https://user-images.githubusercontent.com/66208934/98046192-079b2580-1e2a-11eb-987e-97a2fca31bd3.png

**Comment by TypicalCrusader** [comment]
known issue, copy of #57 and #372

**Comment by BastiYUQ** [comment]
@TypicalCrusader Thanks for looking into this? **Do you know by chance if it is possible to set this message to low priority?** It is currently impossible to play the game in the Chin Bookmark after a certain game time. I tried the same with the Fire Nation and it is also triggering.

**Comment by TypicalCrusader** [comment]
Fixed
