### ISSUE TITLE
Some Casus Belli's are broken

### ISSUE THREAD

**Issue by thelostsoul565** [Rystic/ATLA-restored#481]
After some major changes, seems some things have gone wrong with the CB's
![20201228175644_1](https://user-images.githubusercontent.com/70119367/103253670-f4db3380-4936-11eb-8b8e-4397634277a1.jpg)
![20201228175643_1](https://user-images.githubusercontent.com/70119367/103253672-f60c6080-4936-11eb-8ffb-9bbc90450422.jpg)
![20201228175952_1](https://user-images.githubusercontent.com/70119367/103253674-f60c6080-4936-11eb-9fb8-354907434cb6.jpg)
![20201228175858_1](https://user-images.githubusercontent.com/70119367/103253675-f6a4f700-4936-11eb-9213-7222acf547e6.jpg)

**Comment by TypicalCrusader** [comment]
answer is simple, i copied vanilla cbs file since the previous one was grossly outdated.

**Comment by TypicalCrusader** [comment]
@Rystic you can close it
