### ISSUE TITLE
From Steam: Avatar lost all elements but one after gaining legendary bender trait

### ISSUE THREAD

**Issue by TypicalCrusader** [Rystic/ATLA-restored#504]
1a. The Avatar lost his ability to bend every element except fire. I'm pretty sure this is because he joined the the Agni Kai society. He also gained the 'Legendary Bender' trait (which Avatars shouldn't be able to get"), along with other Agni Kai society traits like blue fire and lightning bending.

**Comment by Tysdas** [comment]
I think I got this one down.
