### ISSUE TITLE
From Steam: Trade Routes Broken

### ISSUE THREAD

**Issue by TypicalCrusader** [Rystic/ATLA-restored#507]
5b. All of the trade posts I own besides the one in my capital duchy have 0 available upgrades.

**Comment by Domaxs** [comment]
Simple misunderstanding, trade posts can only be built on provinces that have the "Potential Trade Post" icon above them on the trade zones map mode. I'll clear this up in my latest PR.

**Comment by Tysdas** [comment]
This is resolved. Misunderstanding.
