### ISSUE TITLE
Unable to Plot to Kill

### ISSUE THREAD

**Issue by agigabyte447** [Rystic/ATLA-restored#55]
As Azulon and Ozai, and a custom Chief of Umiak in the Fall of Chin bookmark, I appear to be completely unable to Plot to Kill anyone. The tooltip for it says that "One of these must be true:" with nothing listed afterward, and that section is marked with an 'x'.

**Comment by agigabyte447** [comment]
I have disabled all other mods besides "Ruler Designer Unlocked" by Mitsuki Akiyama on the Steam Workshop.

**Comment by agigabyte447** [comment]
It just occurred to me that I can send an image for additional clarity, so here (I have tried this with many targets, including a neighboring chief, his child, and one of my own courtiers, plus my husband as you can see here). 
![image](https://user-images.githubusercontent.com/16709819/83467383-61449180-a43f-11ea-84a5-ec7caba184f5.png)

**Comment by jttheghost** [comment]
will be fixed in the steam workshop release tonight
