### ISSUE TITLE
"My kinswoman [me] has written back home..."

### ISSUE THREAD

**Issue by agigabyte447** [Rystic/ATLA-restored#56]
![image](https://user-images.githubusercontent.com/16709819/83467667-3e66ad00-a440-11ea-8cab-85248cfcc96e.png)

**Comment by jttheghost** [comment]
The is due to the way NOMAD.408 is triggered from NOMAD.409 -- need to investigate how vanilla handles events like this

**Comment by TypicalCrusader** [comment]
Possibly fixed by #480
