### ISSUE TITLE
"Centralise the Earth Kingdom" decision has no icon

### ISSUE THREAD

**Issue by unLomTrois** [Rystic/ATLA-restored#596]
![image](https://user-images.githubusercontent.com/51882489/186166908-596f2359-2ed3-4c3b-b100-83a5e912ea0f.png)

**Comment by TypicalCrusader** [comment]
I forgor to add one ;c

**Comment by unLomTrois** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/51882489/187091607-0745b8e9-86d6-4b02-9447-7dced9914edc.png)
