### ISSUE TITLE
Divided disappears almost immediately, sandbenders spawn random event troops

### ISSUE THREAD

**Issue by bboops23** [Rystic/ATLA-restored#63]
The earth kingdom is almost unplayable as Sandbenders event spawn with 4-7k troops and conquer random dutchies everywhere. Maybe disable the event entirely?

The divided disappear almost immediately, conversion speed is way too strong. In the "Fall of Chin" start date the "way of chin" never fades away like it did historically. could be solved by converting AI characters and counties to regular earth spirituality via event until a certain date?

Dont know if this happens everywhere, only encountered it in the fire nation: Claimant hosts become vanilla nomadic clans and raid everything with 4-8k troops, which cant be beaten in the earlier start dates as the fire nation is way too splintered.

**Comment by jttheghost** [comment]
3626622c4728d73520d77c0e6820ae4bdeec9d1f & others fixed this
