### ISSUE TITLE
Entire interface has broken LOC (newest Github version)

### ISSUE THREAD

**Issue by TypicalCrusader** [Rystic/ATLA-restored#78]
![12](https://user-images.githubusercontent.com/66215393/83688964-86c3cd80-a5ee-11ea-8f1b-d331a45f4a8c.png)

![13](https://user-images.githubusercontent.com/66215393/83689119-ca1e3c00-a5ee-11ea-9e49-f9b314b1826e.png)

![14](https://user-images.githubusercontent.com/66215393/83689237-f9cd4400-a5ee-11ea-89b3-e4560f344de9.png)

**Comment by jttheghost** [comment]
Issue with .mod file still having outdated override of localization folder
